config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  root to: 'posts#index'
  devise_for :users, controllers: { registrations: 'registrations' }

  as :user do
    get 'users/edit_password' => 'registrations#edit_password', :as => 'edit_user_registration_password'
    put 'users/edit_password' => 'devise/registrations#update'
  end

  get 'search' => 'search#search'

  resources :users, only: [:index, :show]

  resources :posts, only: [:index, :show, :create, :destroy] do
    resources :photos, only: [:create]
  end

  post 'api/like/:post_id' => 'likes#create'
  delete 'api/like/:post_id' => 'likes#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :user_id, uniqueness: {scope: :post_id}
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :post

  mount_uploader :image, PhotoUploader
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  index_name Rails.application.class.parent_name.underscore
  document_type name.downcase

  settings index: { number_of_shards: 1 } do
    mapping do
      indexes :content
      indexes :user, type: 'nested' do
        # include_root_in_json true
        indexes :name
      end
    end
  end

  def self.search(query)
    __elasticsearch__.search(
        {
            "query": {
                "bool": {
                    "should": [
                        {
                            "multi_match": {
                                "query": query
                            }
                        },
                        {
                            "nested": {
                                "path": "user",
                                "ignore_unmapped": true,
                                "query": {
                                    "bool": {
                                        "should": [
                                            {
                                                "multi_match": {
                                                    "query": query
                                                }
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    ]
                }
            },
            "highlight": {
                "pre_tags": ["<mark>"],
                "post_tags": ["</mark>"],
                "fields": {
                    "content": {},
                    "user.name": {}
                }
            }
        }
    )
  end

  def as_indexed_json(options = nil)
    self.as_json( include: :user )
  end

  belongs_to :user
  has_many :photos, dependent: :destroy
  has_many :likes, -> { order(created_at: :desc) }

  def is_liked(user)
    Like.find_by(user_id: user.id, post_id: id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  index_name Rails.application.class.parent_name.underscore
  document_type name.downcase

  settings index: { number_of_shards: 1 } do
    mapping dynamic: false do
      indexes :name
    end
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { maximum: 50 }

  has_many :posts, dependent: :destroy
  has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:name])
    devise_parameter_sanitizer.permit(:account_update, keys:[:name, :bio, :website])
  end
end

app/controllers/likes_controller.rb
class LikesController <ApplicationController
  before_action :authenticate_user!

  def create
    post = Post.find(params[:post_id])
    likes = post.likes
    like = likes.build(user_id: current_user.id)
    if like.save
      render json: get_response_object(params[:post_id])
    else
      render plain: 'error', status: :internal_server_error
    end
  end

  def destroy
    post = Post.find(params[:post_id])
    like = Like.find_by(user_id: current_user.id, post_id: post.id)

    if like.destroy
      render json: get_response_object(params[:post_id])
    else
      render plain: 'error', status: :internal_server_error
    end
  end

  private

  def like_params
    params.permit :post_id
  end

  def get_response_object(post_id)
    post = Post.find(post_id)
    likes_text = render_to_string partial: 'posts/like_text', locals: {likes: post.likes}
    user_likes = !Like.find_by(user_id: current_user.id, post_id: post_id).nil?

    {
      likes_count: post.likes.size,
      likes_text: likes_text,
      user_likes: user_likes
    }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to new_user_session_path unless user_signed_in?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_post, only: [:show, :destroy]

  def index
    @posts = Post.all.limit(10).includes(:photos, :user, :likes).order('created_at desc')
    @post = Post.new
  end

  def create
    if params.has_key? :images
      @post = current_user.posts.build(post_params)
      if @post.save
        params[:images]&.each do |img|
          @post.photos.create(image: img[1])
        end

        redirect_to root_path
        flash[:notice] = 'Saved...'
      else
        flash[:alert] = 'Something went wrong...'
        redirect_to root_path
      end
    else
      flash[:alert] = 'Something went wrong...'
      redirect_to root_path
    end
  end

  def show
    @photos = @post.photos
    @likes = @post.likes.includes(:user)
    @is_liked = @post.is_liked(current_user)
  end

  def destroy
    if @post.user == current_user
      if @post.destroy
        flash[:notice] = 'Post deleted!'
      else
        flash[:alert] = 'Something went wrong...'
      end
    else
      flash[:notice] = 'You don\'t have permission to delete this post!'
    end
    redirect_to root_path
  end

  private

  def find_post
    @post = Post.find_by id: params[:id]
    return if @post

    flash[:danger] = 'Post doesn\'t exist!'
    redirect_to root_path
  end

  def post_params
    params.require(:post).permit :content
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def edit_password
    @user = current_user
    if request.put?
      if @user.update(user_params)
        # Sign in the user by passing validation in case their password changed
        bypass_sign_in(@user)
        redirect_to root_path
      end
    end
  end

  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    unless params[:query].blank?
      @results = Post.search(params[:query])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url user, size = 80
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    "https://www.gravatar.com/avatar/#{gravatar_id}.jpg?s=#{size}&r=pg"
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="icon" href="<%= image_path 'icon.png' %>" type="image/png">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %><%= render 'shared/navbar'%><% end %>
  <div class="container">
    <%= yield %>
  </div>
  </body>
  <script type="text/javascript">
      <% flash.each do |key, value| %>
        <% type = key.to_s.gsub('alert', 'error').gsub('notice', 'success') %>
        toastr.<%= type %>('<%= value %>');
      <% end %>
  </script>
  <%= render 'shared/footer' %>
</html>

app/views/pages/home.html.erb
<%= link_to 'Log out', destroy_user_session_path, method: :delete %>
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/posts/_like_icon.html.erb
<% liked = is_liked.present? %>
<div class="core-sprite like-icon<% if liked %> filled<% end %> like-action"
     data-action="/api/like/<%= post.id %>" data-liked="<%= liked %>" data-post-id="<%= post.id %>"></div>

app/views/posts/_like_text.html.erb
<% case likes.size %>
<% when 0 %>
  Be the first to like this post!
<% when 1 %>
  <b><%= likes[0].user.name %></b> likes this
<% when 2 %>
  <b><%= likes[0].user.name %></b> and <b><%= likes[1].user.name %></b> like this
<% else %>
  <b><%= likes[0].user.name %></b>, <b><%= likes[1].user.name %></b> and
  <b><span title="<%= likes.slice(2, likes.size - 2).map{|like| like.user.name}.join(', ') %>"><%= pluralize(likes.size - 2, 'other') %></span></b> like this
<% end %>

app/views/posts/_photos.html.erb
<div class="carousel slide" data-ride="carousel" id="carousel-post-<%= post.id %>">
  <div class="carousel-inner">
    <% post.photos.each do |photo| %>
      <div class="carousel-item <% if post.photos.first == photo %>active<% end %>">
        <%= image_tag photo.image.url(:standard), class: 'd-block w-100' %>
      </div>
    <% end %>
  </div>
  <% if post.photos.length > 1 %>
    <a class="carousel-control-prev" href="#carousel-post-<%= post.id %>" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-post-<%= post.id %>" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  <% end %>
</div>

app/views/posts/_posts.html.erb
<% @posts.each do |post| %>
  <div class="card mt-3 post">
    <div class="card-header d-flex align-items-center">
      <%= link_to user_path(post.user)  do %>
        <%= image_tag avatar_url(post.user), class: 'post-author-icon' %>
      <% end %>
      <%= link_to user_path(post.user), class: 'normal-color post-author-text', title: post.user.name do %>
        <b><%= post.user.name %></b>
      <% end %>

      <%= link_to post_path(post), method: :delete, class: 'ml-auto delete-post-icon mx-0 my-auto' do %>
        <i class="fa fa-trash-o" aria-hidden="true"></i>
      <% end %>
    </div>

    <%= render 'photos', { post: post } %>

    <div class="card-body">
      <div class="row-actions d-flex">
        <%= render 'like_icon', { is_liked: post.is_liked(current_user), post: post } %>
        <div class="core-sprite comment-icon" aria-label="Comment"></div>
        <div class="core-sprite bookmark-icon ml-auto" aria-label="Bookmark"></div>
      </div>
      <div class="like-text" data-post-id="<%= post.id %>">
        <%= render 'like_text', { likes: post.likes } %>
      </div>
      <div>
        <span><b><%= post.user.name %></b></span>
        <span><%= post.content %></span>
      </div>
      <%= link_to "#{ time_ago_in_words(post.created_at) } ago", post_path(post), class: 'light-color post-time' %>
      <hr>
      <div class="row-actions d-flex">
        <form action="#" class="w-100">
          <div>
            <textarea class="form-control comment-input border-0" placeholder="Add a comment..." rows="1"></textarea>
          </div>
        </form>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/index.html.erb
<div class="d-flex flex-column align-items-center mt-3">
  <div class="col-xl-7 col-lg-8 col-md-10 col-sm-11 post-card">
    <div class="card">
      <div class="card-header">
        Create Post
      </div>
      <div class="card-body">
        <%= form_for @post, :html => {:multipart => true, :class => 'dropzone upload-images p-0 border-0'} do |f| %>
          <div class="form-group row mt-2">
            <div class="col-auto pr-0">
              <%= image_tag avatar_url(current_user), class: 'post-author-icon' %>
            </div>
            <div class="col pl-0">
              <%= f.text_field :content, class: 'form-control border-0', placeholder: 'Say something about this...' %>
            </div>
          </div>
          <div class="fallback">
            <%= file_field_tag 'images[]', type: :file, multiple: true %>
          </div>
          <div class="dz-message m-0"></div>
          <div class="dropzone-preview mb-3">
            <div class="upload-photos-icon">
              <i class="fa fa-plus fa-2x" aria-hidden="true"></i>
            </div>
          </div>
          <%= f.submit 'Post', class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>

    <div id="posts">
      <%= render 'posts' %>
    </div>

  </div>
</div>

app/views/posts/show.html.erb
<div class="d-flex flex-column align-items-center mt-3">
  <div class="row post box col-xl-10 col-lg-11 col-xs-12">
    <div class="col-lg-8 col-md-7 d-flex post-show-img">
      <div class="align-self-center">
        <%= render 'photos', { post: @post } %>
      </div>
    </div>
    <div class="col-lg-4 col-md-5 mt-sm-4 mt-md-0 card">
      <div class="row px-3 d-flex align-items-center card-header">
        <%= link_to user_path(@post.user), class: 'no-text-decoration' do %>
          <%= image_tag avatar_url(@post.user), class: 'post-author-icon' %>
        <% end %>
        <%= link_to user_path(@post.user), class: 'normal-color no-text-decoration d-flex align-self-center', title: @post.user.name do %>
          <b><%= @post.user.name %></b>
        <% end %>

        <%= link_to post_path(@post), method: :delete, class: 'ml-auto delete-post-icon mx-0 my-auto' do %>
          <i class="fa fa-trash-o" aria-hidden="true"></i>
        <% end %>
      </div>
      <hr class="mb-0">
      <div class="comment-list py-2">
        <% if @post.content.present? %>
          <div>
            <span><b><%= @post.user.name %></b></span>
            <span><%= @post.content %></span>
          </div>
        <% end %>
        <%# load comment %>
        <% 100.times do %>
          <div>
            <span><b>Hallo M151 Instagram</b></span>
            <span>Kommentar</span>
          </div>
        <% end %>
      </div>
      <hr class="mt-0">
      <div class="row-actions d-flex">
        <%= render 'like_icon', { is_liked: @is_liked, post: @post } %>
        <div class="core-sprite comment-icon" aria-label="Comment"></div>
        <div class="core-sprite bookmark-icon ml-auto" aria-label="Bookmark"></div>
      </div>
      <div class="like-text" data-post-id="<%= @post.id %>"><%= render 'like_text', { likes: @post.likes } %></div>
      <div class="light-color post-time"><%= time_ago_in_words(@post.created_at) %> ago</div>
      <hr>
      <div class="row-actions d-flex">
        <form action="#" class="w-100">
          <div>
            <textarea class="form-control comment-input border-0" placeholder="Add a comment ..." rows="1"></textarea>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/search/_post.html.erb
<% post = Post.find(result.id) %>

<div class="card mt-3 post">
  <div class="card-header d-flex align-items-center">
    <%= link_to user_path(post.user)  do %>
      <%= image_tag avatar_url(post.user), class: 'post-author-icon' %>
    <% end %>
    <%= link_to user_path(post.user), class: 'normal-color post-author-text', title: result.user.name do %>
      <b><% if !result.highlight.nil? && !result.highlight['user.name'].nil? %><%= raw result.highlight['user.name'].join(' ') %><% else %><%= result.user.name %><% end %></b>
    <% end %>

    <%= link_to post_path(post), method: :delete, class: 'ml-auto delete-post-icon mx-0 my-auto' do %>
      <i class="fa fa-trash-o" aria-hidden="true"></i>
    <% end %>
  </div>

  <%= render 'posts/photos', { post: post } %>

  <div class="card-body">
    <div class="row-actions d-flex">
      <%= render 'posts/like_icon', { is_liked: post.is_liked(current_user), post: post } %>
      <div class="core-sprite comment-icon" aria-label="Comment"></div>
      <div class="core-sprite bookmark-icon ml-auto" aria-label="Bookmark"></div>
    </div>
    <div class="like-text" data-post-id="<%= result.id %>">
      <%= render 'posts/like_text', { likes: post.likes } %>
    </div>
    <div>
      <span><b><%= result.user.name %></b></span>
      <span><% if !result.highlight.nil? && !result.highlight.content.nil? %><%= raw result.highlight.content.join(' ') %><% else %><%= result.content %><% end %></span>
    </div>
    <%= link_to "#{ time_ago_in_words(result.created_at) } ago", post_path(post), class: 'light-color post-time' %>
    <hr>
    <div class="row-actions d-flex">
      <form action="#" class="w-100">
        <div>
          <textarea class="form-control comment-input border-0" placeholder="Add a comment..." rows="1"></textarea>
        </div>
      </form>
    </div>
  </div>
</div>

app/views/search/search.html.erb
<div class="d-flex flex-column align-items-center mt-3">
  <div class="col-xl-7 col-lg-8 col-md-10 col-sm-11 post-card">
    <% unless @results.nil? %>
      <% if @results.empty? %>
        <h2>No posts found matching your query.</h2>
      <% else %>
        <h2>Search results</h2>

        <% @results.each do |result| %>
          <%= render :partial => 'search/post', :locals => { result: result } %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar">
      <div class="navbar-nav mx-auto">
        <a class="nav-item nav-link" href="#">ABOUT US</a>
        <a class="nav-item nav-link" href="#">SUPPORT</a>
        <a class="nav-item nav-link" href="#">BLOG</a>
        <a class="nav-item nav-link" href="#">PRESS</a>
        <a class="nav-item nav-link" href="#">API</a>
        <a class="nav-item nav-link" href="#">JOB</a>
        <a class="nav-item nav-link" href="#">PRIVACY</a>
        <a class="nav-item nav-link" href="#">TERMS</a>
        <a class="nav-item nav-link" href="#">DIRECTORY</a>
        <a class="nav-item nav-link" href="#">LANGUAGE</a>
      </div>
    </div>
  </nav>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-white">
  <div class="container-fluid">

    <%=link_to '', root_path, { class: 'navbar-brand core-sprite', aria_label: 'Instagram logo' } %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <%# TODO: Update me %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <form class="form-inline my-2 my-lg-0 ml-md-auto" method="get" action="/search">
        <input class="form-control mr-sm-2 text-center" type="search" placeholder="Search" aria-label="Search" name="query" required>
      </form>
      <ul class="navbar-nav ml-md-auto">
        <li class="nav-item">
          <a class="nav-link core-sprite explore-icon" href="#" aria-label="Explore"></a>
        </li>
        <li class="nav-item">
          <a class="nav-link core-sprite notification-icon" href="#" aria-label="Notification"></a>
        </li>
        <li class="nav-item">
          <%= link_to '', user_path(current_user), class: 'nav-link core-sprite profile-icon', aria_label: 'User' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/users/show.html.erb
<div class="row justify-content-md-center profile-wrapper">
  <div class="col-md-4 text-center">
    <%= image_tag avatar_url(@user, 152), width: '152', height: '152', class: 'round-img' %>
  </div>
  <div class="col-md-8">
    <div class="row align-items-center">
      <div class="username"><%= @user.name %></div>
      <% if @user === current_user %>
        <%= link_to 'Edit Profile', edit_user_registration_path, class: 'btn btn-outline-dark common-btn edit-profile-btn' %>
        <button type="button" class="core-sprite settings-icon settings" data-toggle="modal" data-target="#user-settings-modal"></button>

        <div class="modal fade" id="user-settings-modal" tabindex="-1" role="dialog" aria-labelledby="user-settings-modal-label" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="user-settings-modal-label">Settings</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="list-group text-center">
                <a href="#" class="list-group-item list-group-item-action">Change Password</a>
                <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'list-group-item list-group-item-action' %>
                <a href="#" class="list-group-item list-group-item-action" data-dismiss="modal">Cancel</a>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="row">
      <p class="email"><%= @user.email %></p>
    </div>
  </div>
</div>